/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Joystick */

#ifndef _Included_Joystick
#define _Included_Joystick
#ifdef __cplusplus
extern "C" {
#endif
#undef Joystick_BUTTON1
#define Joystick_BUTTON1 1L
#undef Joystick_BUTTON2
#define Joystick_BUTTON2 2L
#undef Joystick_BUTTON3
#define Joystick_BUTTON3 4L
#undef Joystick_BUTTON4
#define Joystick_BUTTON4 8L
/*
 * Class:     Joystick
 * Method:    getNumDevs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_joystick_Joystick_getNumDevs
  (JNIEnv *, jobject);

/*
 * Class:     Joystick
 * Method:    getXPos
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_joystick_Joystick_getXPos
  (JNIEnv *, jobject, jint);

/*
 * Class:     Joystick
 * Method:    getYPos
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_joystick_Joystick_getYPos
  (JNIEnv *, jobject, jint);

/*
 * Class:     Joystick
 * Method:    getZPos
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_joystick_Joystick_getZPos
  (JNIEnv *, jobject, jint);

/*
 * Class:     Joystick
 * Method:    getButtons
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_joystick_Joystick_getButtons
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
